---
project:
  description: Markdown::Render
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm-module: Markdown::Render
min-perl-version: 5.010
dependencies:
  requires: requires
  test-requires: test-requires
  recommends: recommends
  suggests: suggests
path:
  pm-module: lib
  exe-files: bin
  tests: t
extra-files:
  - ChangeLog
  - README.md
  - share:
      - README.md
resources:
  bugtracker:
    mailto: rclauer@gmail.com
    web: https://github.com/rlauer6/Markdown-Render/issues
  homepage: https://github.com/rlauer6/Markdown-Render
  repository:
    type: git
    url: git@github.com:rlauer6/Markdown-Render.git
    web: https://github.com/rlauer6/Markdown-Render
